# Generated by Django 3.2 on 2021-04-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollsBalls',
            fields=[
                ('id', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
    ]
